/*
 * This file is the main driver for the Midnight anonymous feedback board example.
 * The entry point is the run function, at the end of the file.
 * We expect the startup files (standalone.ts, preview.ts, preprod.ts) to
 * call run with some specific configuration that sets the network addresses
 * of the servers this file relies on.
 */

import { createInterface, type Interface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import { WebSocket } from 'ws';
import {
  FeedbackBoardAPI,
  type FeedbackBoardDerivedState,
  feedbackBoardPrivateStateKey,
  type FeedbackBoardProviders,
  type DeployedFeedbackBoardContract,
  type PrivateStateId,
} from '../../api/src/index';
import { type WalletFacade } from '@midnight-ntwrk/wallet-sdk-facade';
import { ledger, type Ledger } from '../../contract/src/managed/feedback-board/contract/index.js';
import { NodeZkConfigProvider } from '@midnight-ntwrk/midnight-js-node-zk-config-provider';
import { indexerPublicDataProvider } from '@midnight-ntwrk/midnight-js-indexer-public-data-provider';
import { httpClientProofProvider } from '@midnight-ntwrk/midnight-js-http-client-proof-provider';
import { type Logger } from 'pino';
import { type Config, StandaloneConfig } from './config.js';
import { levelPrivateStateProvider } from '@midnight-ntwrk/midnight-js-level-private-state-provider';
import { type ContractAddress } from '@midnight-ntwrk/midnight-js-protocol/compact-runtime';
import { assertIsContractAddress, toHex } from '@midnight-ntwrk/midnight-js-utils';
import { TestEnvironment } from '@midnight-ntwrk/testkit-js';
import { MidnightWalletProvider } from './midnight-wallet-provider';
import { randomBytes } from '../../api/src/utils';
import { unshieldedToken } from '@midnight-ntwrk/midnight-js-protocol/ledger';
import { syncWallet, waitForUnshieldedFunds } from './wallet-utils';
import { generateDust } from './generate-dust';
import { FeedbackBoardPrivateState } from '../../contract/src/witnesses.js';

// @ts-expect-error: It's needed to enable WebSocket usage through apollo
globalThis.WebSocket = WebSocket;

/* **********************************************************************
 * getFeedbackBoardLedgerState: a helper that queries the current state of
 * the data on the ledger, for a specific feedback board contract. Note
 * that the Ledger type returned here is not some generic, abstract ledger
 * object, but specifically the type generated by the Compact compiler to
 * correspond to the ledger declaration in the feedback board contract.
 */

export const getFeedbackBoardLedgerState = async (
  providers: FeedbackBoardProviders,
  contractAddress: ContractAddress,
): Promise<Ledger | null> => {
  assertIsContractAddress(contractAddress);
  const contractState = await providers.publicDataProvider.queryContractState(contractAddress);
  return contractState != null ? ledger(contractState.data) : null;
};

/* **********************************************************************
 * deployOrJoin: returns a contract, by prompting the user about
 * whether to deploy a new one or join an existing one and then
 * calling the appropriate helper.
 */

const DEPLOY_OR_JOIN_QUESTION = `
You can do one of the following:
  1. Deploy a new feedback board contract
  2. Join an existing feedback board contract
  3. Exit
Which would you like to do? `;

const deployOrJoin = async (
  providers: FeedbackBoardProviders,
  rli: Interface,
  logger: Logger,
): Promise<FeedbackBoardAPI | null> => {
  let api: FeedbackBoardAPI | null = null;

  while (true) {
    const choice = await rli.question(DEPLOY_OR_JOIN_QUESTION);
    switch (choice) {
      case '1':
        api = await FeedbackBoardAPI.deploy(providers, logger);
        logger.info(`Deployed contract at address: ${api.deployedContractAddress}`);
        return api;
      case '2':
        api = await FeedbackBoardAPI.join(providers, await rli.question('What is the contract address (in hex)? '), logger);
        logger.info(`Joined contract at address: ${api.deployedContractAddress}`);
        return api;
      case '3':
        logger.info('Exiting...');
        return null;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * displayLedgerState: shows the values of each of the fields declared
 * by the contract to be in the ledger state of the feedback board.
 */

const displayLedgerState = async (
  providers: FeedbackBoardProviders,
  deployedFeedbackBoardContract: DeployedFeedbackBoardContract,
  logger: Logger,
): Promise<void> => {
  const contractAddress = deployedFeedbackBoardContract.deployTxData.public.contractAddress;
  const ledgerState = await getFeedbackBoardLedgerState(providers, contractAddress);
  if (ledgerState === null) {
    logger.info(`There is no feedback board contract deployed at ${contractAddress}`);
  } else {
    logger.info(`Current admin key is: '${toHex(ledgerState.admin)}'`);
    logger.info(`Current round is: ${ledgerState.round}`);
    logger.info(`Current member count is: ${ledgerState.members.size()}`);
    logger.info(`Current feedback count is: ${ledgerState.feedbacks.size()}`);
    for (const [id, content] of ledgerState.feedbacks) {
      logger.info(`  #${id}: ${content}`);
    }
  }
};

/* **********************************************************************
 * displayPrivateState: shows the hex-formatted value of the secret key.
 */

const displayPrivateState = async (providers: FeedbackBoardProviders, logger: Logger): Promise<void> => {
  const privateState = await providers.privateStateProvider.get(feedbackBoardPrivateStateKey);
  if (privateState === null) {
    logger.info(`There is no existing feedback board private state`);
  } else {
    logger.info(`Current secret key is: ${toHex(privateState.secretKey)}`);
  }
};

/* **********************************************************************
 * displayDerivedState: shows the values of derived state which is made
 * by combining the ledger state with private state. In this example, the
 * derived state compares the caller's own admin/member key commitments
 * with the ones on the ledger to determine the caller's role.
 */

const displayDerivedState = (state: FeedbackBoardDerivedState | undefined, logger: Logger) => {
  if (state === undefined) {
    logger.info(`No feedback board state currently available`);
  } else {
    logger.info(`Current round is: ${state.round}`);
    logger.info(`Are you the admin? '${state.isAdmin ? 'yes' : 'no'}'`);
    logger.info(`Are you a registered member? '${state.isMember ? 'yes' : 'no'}'`);
    logger.info(`Have you submitted feedback this round? '${state.hasSubmittedThisRound ? 'yes' : 'no'}'`);
    logger.info(`Your member key (to hand to the admin) is: '${toHex(state.ownMemberKey)}'`);
    logger.info(`Feedback so far (${state.feedbacks.length}):`);
    for (const feedback of state.feedbacks) {
      logger.info(`  #${feedback.id}: ${feedback.content}`);
    }
  }
};

/* **********************************************************************
 * mainLoop: the main interactive menu of the feedback board CLI.
 * Before starting the loop, the user is prompted to deploy a new
 * contract or join an existing one.
 */

const MAIN_LOOP_QUESTION = `
You can do one of the following:
  1. Register as the admin (only works once, for the first caller)
  2. Add a member (admin only)
  3. Open a new feedback round (admin only)
  4. Submit feedback (members only)
  5. Display the current ledger state (known by everyone)
  6. Display the current private state (known only to this DApp instance)
  7. Display the current derived state (known only to this DApp instance)
  8. Exit
Which would you like to do? `;

const mainLoop = async (providers: FeedbackBoardProviders, rli: Interface, logger: Logger): Promise<void> => {
  const feedbackBoardApi = await deployOrJoin(providers, rli, logger);
  if (feedbackBoardApi === null) {
    return;
  }
  let currentState: FeedbackBoardDerivedState | undefined;
  const stateObserver = {
    next: (state: FeedbackBoardDerivedState) => (currentState = state),
  };
  const subscription = feedbackBoardApi.state$.subscribe(stateObserver);
  try {
    while (true) {
      const choice = await rli.question(MAIN_LOOP_QUESTION);
      try {
        switch (choice) {
          case '1':
            await feedbackBoardApi.registerAdmin();
            break;
          case '2': {
            const memberPk = await rli.question(`What is the new member's public key (in hex)? `);
            await feedbackBoardApi.addMember(Buffer.from(memberPk, 'hex'));
            break;
          }
          case '3':
            await feedbackBoardApi.openNewRound();
            break;
          case '4': {
            const content = await rli.question(`What feedback do you want to submit? `);
            await feedbackBoardApi.submitFeedback(content);
            break;
          }
          case '5':
            await displayLedgerState(providers, feedbackBoardApi.deployedContract, logger);
            break;
          case '6':
            await displayPrivateState(providers, logger);
            break;
          case '7':
            displayDerivedState(currentState, logger);
            break;
          case '8':
            logger.info('Exiting...');
            return;
          default:
            logger.error(`Invalid choice: ${choice}`);
        }
      } catch (e) {
        logError(logger, e);
        logger.info('Returning to main menu...');
      }
    }
  } finally {
    // While we allow errors to bubble up to the 'run' function, we will always need to dispose of the state
    // subscription when we exit.
    subscription.unsubscribe();
  }
};

/* ***********************************************************************
 * This seed gives access to tokens minted in the genesis block of a local development node - only
 * used in standalone networks to build a wallet with initial funds.
 */
const GENESIS_MINT_WALLET_SEED = '0000000000000000000000000000000000000000000000000000000000000001';

/* **********************************************************************
 * buildWallet: unless running in a standalone (offline) mode,
 * prompt the user to tell us whether to create a new wallet
 * or recreate one from a prior seed.
 */

const WALLET_LOOP_QUESTION = `
You can do one of the following:
  1. Build a fresh wallet
  2. Build wallet from a seed
  3. Exit
Which would you like to do? `;

const buildWallet = async (config: Config, rli: Interface, logger: Logger): Promise<string | undefined> => {
  if (config instanceof StandaloneConfig) {
    return GENESIS_MINT_WALLET_SEED;
  }
  while (true) {
    const choice = await rli.question(WALLET_LOOP_QUESTION);
    switch (choice) {
      case '1':
        return toHex(randomBytes(32));
      case '2':
        return await rli.question('Enter your wallet seed: ');
      case '3':
        logger.info('Exiting...');
        return undefined;
      default:
        logger.error(`Invalid choice: ${choice}`);
    }
  }
};

/* **********************************************************************
 * run: the main entry point that starts the whole feedback board CLI.
 *
 * If called with a Docker environment argument, the application
 * will wait for Docker to be ready before doing anything else.
 */

export const run = async (config: Config, testEnv: TestEnvironment, logger: Logger): Promise<void> => {
  const rli = createInterface({ input, output, terminal: true });
  const providersToBeStopped: MidnightWalletProvider[] = [];
  try {
    const envConfiguration = await testEnv.start();
    logger.info(`Environment started with configuration: ${JSON.stringify(envConfiguration)}`);
    const seed = await buildWallet(config, rli, logger);
    if (seed === undefined) {
      return;
    }
    const walletProvider = await MidnightWalletProvider.build(logger, envConfiguration, seed);
    providersToBeStopped.push(walletProvider);
    const walletFacade: WalletFacade = walletProvider.wallet;

    await walletProvider.start();

    const unshieldedState = await waitForUnshieldedFunds(logger, walletFacade, envConfiguration, unshieldedToken());
    const nightBalance = unshieldedState.balances[unshieldedToken().raw];
    if (nightBalance === undefined) {
      logger.info('No funds received, exiting...');
      return;
    }
    logger.info(`Your NIGHT wallet balance is: ${nightBalance}`);

    if (config.generateDust) {
      const dustGeneration = await generateDust(logger, seed, unshieldedState, walletFacade);
      if (dustGeneration) {
        logger.info(`Submitted dust generation registration transaction: ${dustGeneration}`);
        await syncWallet(logger, walletFacade);
      }
    }

    const zkConfigProvider = new NodeZkConfigProvider<
      'registerAdmin' | 'addMember' | 'openNewRound' | 'submitFeedback'
    >(config.zkConfigPath);
    const providers: FeedbackBoardProviders = {
      privateStateProvider: levelPrivateStateProvider<PrivateStateId, FeedbackBoardPrivateState>({
        privateStateStoreName: config.privateStateStoreName,
        signingKeyStoreName: `${config.privateStateStoreName}-signing-keys`,
        privateStoragePasswordProvider: () => {
          return 'FeedbackBoard-Test-2026!';
        },
        accountId: seed,
      }),
      publicDataProvider: indexerPublicDataProvider(envConfiguration.indexer, envConfiguration.indexerWS),
      zkConfigProvider: zkConfigProvider,
      proofProvider: httpClientProofProvider(envConfiguration.proofServer, zkConfigProvider),
      walletProvider: walletProvider,
      midnightProvider: walletProvider,
    };
    await mainLoop(providers, rli, logger);
  } catch (e) {
    logError(logger, e);
    logger.info('Exiting...');
  } finally {
    try {
      rli.close();
      rli.removeAllListeners();
    } catch (e) {
      logError(logger, e);
    } finally {
      try {
        for (const wallet of providersToBeStopped) {
          logger.info('Stopping wallet...');
          await wallet.stop();
        }
        if (testEnv) {
          logger.info('Stopping test environment...');
          await testEnv.shutdown();
        }
      } catch (e) {
        logError(logger, e);
      }
    }
  }
};

function logError(logger: Logger, e: unknown) {
  if (e instanceof Error) {
    logger.error(`Found error '${e.message}'`);
    logger.debug(`${e.stack}`);
  } else {
    logger.error(`Found error (unknown type)`);
  }
}
